### ISSUE TITLE
Donate section is formatted incorrectly(?)

### ISSUE THREAD

**Issue by OneShot-Niko** [Snail-IDE/Snail-IDE-Website#1]
Unsure how to explain, thus I'll just leave this recording here:

https://github.com/Snail-IDE/Snail-IDE-Website/assets/150537842/004c7a99-d8d6-4610-941a-e861b29b088d

Basically, PenguinMod's URL is replaced with Snail IDE's rather than being seperate, Turbowarp & Scratch's donate URLs are just not even hyperlinked.
Cannot find the footer, so making an issue instead.
(thank you for enabling issues by the way)

EDIT: This includes the normal donate page technically, hyperlinks don't exist there.

**Comment by nmsderp** [comment]
Fixed

**Comment by OneShot-Niko** [comment]
> Fixed

Epic - ty
Though shouldn't your own donate page also be there? And [/donate](https://snail-ide.vercel.app/donate) appears to still have it unformatted.
Apologies for the nitpick though.

**Comment by nmsderp** [comment]
we don't need the donate page anymore since we don't use repl.it anymore

**Comment by OneShot-Niko** [comment]
> we don't need the donate page anymore since we don't use repl.it anymore

Alright then, apologies.
