### ISSUE TITLE
upload

### ISSUE THREAD

**Issue by coding2234** [Snail-IDE/Snail-IDE-Website#10]
I can't upload projects
before I click on upload
![Screenshot (7)](https://github.com/user-attachments/assets/260a3fea-1864-49ee-ac1e-082b98edb163)
after I click on upload
![Screenshot (8)](https://github.com/user-attachments/assets/8bfc72a4-6fea-49e2-a6d2-e3a8cb73fe76)

**Comment by nmsderp** [comment]
you must rank up first, upload a few projects without any non-scratch extensions first then rank up
