### ISSUE TITLE
Should we add giscus?

### ISSUE THREAD

**Issue by someCatInTheWorld** [Snail-IDE/Snail-IDE-Website#3]
https://giscus.app/

We could add it to pages like the Terms of Service and if it's possible, user pages.

**Comment by nmsderp** [comment]
Probably not, scratch team would get pretty mad

**Comment by someCatInTheWorld** [comment]
> Probably not, scratch team would get pretty mad

How?

**Comment by nmsderp** [comment]
its unmoderated chat right on the website
